baseURL = 'https://ddp.im/'
disableKinds = ['taxonomy', 'term', 'section']
disableHugoGeneratorInject = true
enableRobotsTXT = true

defaultContentLanguage = 'de'
[languages]
	[languages.de]
		contentDir = 'content/de'
		disabled = false
		languageCode = 'de-DE'
		languageDirection = 'ltr'
		languageName = 'German'
		weight = 1
	[languages.en]
		contentDir = 'content/en'
		disabled = false
		languageCode = 'en-US'
		languageDirection = 'ltr'
		languageName = 'English'
		weight = 2

[markup]
	[markup.goldmark.renderer]
		unsafe = true